services:
  - type: web
    name: ecoleta-server
    env: node
    plan: free
    autoDeploy: true

    buildCommand: npm ci && npm run build
    startCommand: >
      bash -lc 'mkdir -p /tmp/uploads &&
      (cp -R uploads/. /tmp/uploads/ 2>/dev/null || true) &&
      npm run knex:migrate &&
      npm run knex:seed &&
      npm run start'

    healthCheckPath: /healthz

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILE
        value: /tmp/database.sqlite
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: APP_URL
        value: https://ecoleta-server.onrender.com
      - key: NPM_CONFIG_PRODUCTION
        value: "false"