services:
  - type: web
    name: ecoleta-server
    env: node
    plan: free
    autoDeploy: true

    buildCommand: npm ci && npm run build
    # cria /var/data/uploads, copia uploads do repo (se existirem),
    # roda migrations + seeds e inicia o server
    startCommand: >
      bash -lc 'mkdir -p /var/data/uploads &&
      (cp -R uploads/. /var/data/uploads/ 2>/dev/null || true) &&
      npm run knex:migrate &&
      npm run knex:seed &&
      npm run start'

    healthCheckPath: /healthz

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILE
        value: /var/data/database.sqlite
      - key: UPLOAD_DIR
        value: /var/data/uploads
      - key: APP_URL
        value: https://ecoleta-server.onrender.com
      - key: NPM_CONFIG_PRODUCTION
        value: "false"

    disk:
      name: database
      mountPath: /var/data
      sizeGB: 1